service: sls-node-graphql

plugins:
  - serverless-offline
  
provider:
  name: aws
  runtime: nodejs12.x

functions:
  query_graphql:
    handler: handler.query_graphql
    events:
      - http:
          path: /graphql
          method: POST

